name: stna_lms_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.2.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  permission_handler: ^8.3.0
  flutter_svg: ^0.23.0
  http: ^0.13.1
  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_rating_bar: ^4.0.0
  extended_nested_scroll_view: ^5.1.3
  font_awesome_flutter: ^9.0.0
  flutter_widget_from_html_core: ^0.8.5+3
  skeleton_loader: ^2.0.0+4
  youtube_player_flutter: ^8.1.0
  http_auth: ^1.0.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^8.1.1+1
  rxdart: ^0.27.4
  flutter_smart_dialog: ^4.5.4+1
  percent_indicator: ^4.2.2
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  just_audio: ^0.9.24
  day: ^0.8.0
  jwt_decode: ^0.3.1
  image_picker: ^0.8.5
  avatar_glow: ^2.0.2
  tab_indicator_styler: ^2.0.0
  carousel_slider: ^4.1.1
  uuid: ^3.0.6
  youtube_metadata: ^1.0.1
  chewie: ^1.3.4
  video_player: ^2.4.6
  dotted_border: 2.0.0
  url_launcher: ^6.1.1
  overlay_support: ^2.0.1
  firebase_analytics: ^9.1.10
  persistent_bottom_nav_bar: ^4.0.2
  flutter_speed_dial: ^6.0.0
  back_button_interceptor: ^6.0.1
  loading_more_list: ^4.1.2
  expansion_tile_card: 2.0.0
  recase: ^4.0.0
  lazy_load_scrollview: ^1.3.0
  equatable: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  package_info_plus: ^1.4.2
  version: ^3.0.2
  wakelock: ^0.6.2
  appcheck: ^1.0.5
  flutter_otp_text_field: ^1.1.1
  logger_console: ^2.0.0
  pin_code_fields: ^7.4.0
  universal_io: ^2.0.4
  flutter_web_frame: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  import_sorter: ^4.6.0
  flutter_markdown: 0.6.10
  badges: ^2.0.3

flutter_icons:
  ios: true
  image_path: "images/ic_launcher_ios.png"
  android: true
  adaptive_icon_foreground: "images/ic_launcher_android.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: "images/logo-transparent.png"
  color: "EFFAFD"
  fill: false

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/layout/
    - images/layout/social/
    - images/quiz/
    - images/utility/
    - images/placeholders/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 400
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 500
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
